name: Build Custom Image

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: \( {{ github.workflow }}- \){{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          recipe: ${{ matrix.recipe }}
          push: true
          # ניסיון לכבות חתימה דרך build-opts
          build-opts: "--no-sign"
